apiVersion: apps/v1
kind: Deployment
metadata:
  name: tastytreat
spec:
  selector:
    matchLabels:
      app: tastytreat
  replicas: 1
  template:
    metadata:
      labels:
        app: tastytreat
    spec:
      containers:
      - name: tastytreat
        image: tastytreat
        ports:
        - containerPort: 80