apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-demo
spec:
  selector:
    matchLabels:
      app: microservices-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: microservices-demo
    spec:
      containers:
      - name: microservices-demo
        image: microservices-demo
        ports:
        - containerPort: 80